image: ubuntu:artful

before_script: 
  - |
    apt-get update -qq -y --no-install-recommends && \
    apt-get install -qq -y --fix-missing pkg-config && \
    apt-get install -qq -y --no-install-recommends \
                    bash shellcheck devscripts make \
                    cmake cmake-data g++ python \
                    binutils-dev libcurl4-openssl-dev zlib1g-dev \
                    libdw-dev libiberty-dev wget ca-certificates
  - wget -O kcov-33.tar.gz https://github.com/SimonKagstrom/kcov/archive/v33.tar.gz
  - |
    tar zxf kcov-33.tar.gz && mkdir kcov-build && \
    cd kcov-build && cmake ../kcov-33 && make && make install && cd ..

stages:
  - test

job_test:
  stage: test
  coverage: '/^Coverage:\s+([+-]?(?:\d*\.)?\d+%)\s*$/'
  script:
    - make test
    - ls tests/cov
    - make covreport
    - shellcheck -s sh sh-ultramunge.sh
    - checkbashisms -fnp sh-ultramunge.sh
  tags:
    - shared
