image: ubuntu:artful

before_script: 
  - |
    apt-get update -qq -y --no-install-recommends && \
    apt-get install -qq -y --fix-missing pkg-config && \
    apt-get install -qq -y --no-install-recommends \
                    bash shellcheck devscripts make \
                    cmake cmake-data g++ python \
                    binutils-dev libcurl4-openssl-dev zlib1g-dev \
                    libdw-dev libiberty-dev git ca-certificates
  - git clone https://github.com/SimonKagstrom/kcov.git /kcov-src
  - |
    mkdir /kcov-build && pushd /kcov-build \
    && cmake /kcov-src && make && make install && popd

stages:
  - test

job_test:
  stage: test
  coverage: '/^Coverage:\s+([+-]?(?:\d*\.)?\d+%)\s*$/'
  script:
    - make test
    - ls tests/cov
    - make covreport
    - shellcheck -s sh sh-ultramunge.sh
    - checkbashisms -fnp sh-ultramunge.sh
  tags:
    - shared
