image: ubuntu:artful

before_script:
  - |
    apt-get update -qq -y --no-install-recommends && \
    apt-get install -qq -y --no-install-recommends \
                    shellcheck devscripts

stages:
  - test

job_test:
  stage: test
  tags:
    - shared
  image: docker:latest
  variables:
    DOCKER_DRIVER: overlay2
  services:
    - docker:dind
  before_script:
    - docker info
  script:
    - docker build -t sh-ultramunge-test .
    - docker run --rm sh-ultramunge-test make test
  after_script:
    - docker rmi sh-ultramunge-test:latest
  coverage: '/^Coverage:\s+([+-]?(?:\d*\.)?\d+%)\s*$/'

job_lint:
  stage: test
  allow_failure: true
  tags:
    - shared
  script:
    - shellcheck -s sh sh-ultramunge.sh
    - checkbashisms -fnpx sh-ultramunge.sh
