image: fedora:latest

before_script: 
  - |
    dnf install bash ShellCheck devscripts make \
                cmake cmake-data gcc-c++ python \
                elfutils-libelf-devel libcurl-devel binutils-devel \
                elfutils-devel git ca-certificates
  - git clone https://github.com/SimonKagstrom/kcov.git /kcov-src
  - |
    mkdir /kcov-build && pushd /kcov-build \
    && cmake /kcov-src && make && make install && popd
  - which kcov; kcov --version

stages:
  - test

job_test:
  stage: test
  coverage: '/^Coverage:\s+([+-]?(?:\d*\.)?\d+%)\s*$/'
  script:
    - make test
    - ls tests/cov
    - cat tests/cov/runall.sh*/coverage.json
    - make covreport
    - shellcheck -s sh sh-ultramunge.sh
    - checkbashisms -fnp sh-ultramunge.sh
  tags:
    - shared
