image: ragnaroek/kcov:latest

before_script: 
  - |
    apt-get update -qq -y --no-install-recommends && \
    apt-get install -qq -y --no-install-recommends \
                    bash shellcheck devscripts make

stages:
  - test

job_test:
  stage: test
  coverage: '/^Coverage:\s+([+-]?(?:\d*\.)?\d+%)\s*$/'
  script:
    - make test
    - ls tests/cov
    - make covreport
    - shellcheck -s sh sh-ultramunge.sh
    - checkbashisms -fnp sh-ultramunge.sh
  tags:
    - shared
